Project_EOS/Areas/Admin/Controllers/EmployeesManageController.cs
using Project_EOS.Models.Dao;
using Project_EOS.Models.Entities;
using System;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_EOS.Areas.Admin.Controllers
{
    public class EmployeesManageController : Controller
    {
        // GET: Admin/EmployeesManage
        public ActionResult Index()
        {
            var employees = EmployeeDAO.Instance.GetAllEmployees();
            var services = ServiceDAO.Instance.GetAllServices(); // Lấy danh sách dịch vụ từ ServiceDAO
            ViewBag.employees = employees;
            ViewBag.Departments = new SelectList(EmployeeDAO.Instance.GetAllDepartments(), "DepartmentID", "DepartmentName");
            ViewBag.Services = new SelectList(services, "ServiceID", "ServiceName"); // Truyền danh sách dịch vụ vào ViewBag
            return View();
        }


        public ActionResult Create()
        {
            var departments = EmployeeDAO.Instance.GetAllDepartments();
            ViewBag.Departments = new SelectList(departments, "DepartmentID", "DepartmentName");
            return View();
        }

        [HttpPost]
        public JsonResult AddEmployee(NewEmployeeDTO model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.Email = HttpUtility.UrlDecode(model.Email);

                    var newEmployee = new Employee
                    {
                        EmployeeName = model.EmployeeName,
                        DepartmentID = model.DepartmentID,
                        Designation = model.Designation,
                        Email = model.Email,
                        Salary = model.Salary,
                        ServiceID = model.ServiceID,
                        JoinDate = model.JoinDate,
                        Is_Active = model.Is_Active,
                        // Tạo giá trị ngẫu nhiên cho Username và Password
                        Username = GenerateRandomString(6),
                        Password = GenerateRandomPassword(8)
                    };

                    EmployeeDAO.Instance.AddEmployee(newEmployee);

                    return Json(new { success = true });
                }
                catch (Exception ex)
                {
                    return Json(new { success = false, message = ex.Message });
                }
            }
            else
            {
                return Json(new { success = false, message = "Invalid input data" });
            }
        }

        public ActionResult EmployeeDetail(int employeeID)
        {
            var employee = EmployeeDAO.Instance.GetEmployeeById(employeeID);
            if (employee != null)
            {
                ViewBag.Employee = employee;

                // Lấy danh sách dịch vụ từ ServiceDAO
                var services = ServiceDAO.Instance.GetAllServices();
                ViewBag.Services = new SelectList(services, "ServiceID", "ServiceName");

                // Lấy danh sách phòng ban từ EmployeeDAO
                ViewBag.Departments = new SelectList(EmployeeDAO.Instance.GetAllDepartments(), "DepartmentID", "DepartmentName");

                return View(employee);
            }
            else
            {
                return HttpNotFound();
            }
        }


        [HttpPost]
        public JsonResult EditEmployee(EmployeeViewModel model)
        {
            try
            {
                Console.WriteLine("Start processing EditEmployee action");
                Console.WriteLine($"Employee ID: {model.EmployeeID}");
                Console.WriteLine($"Department ID: {model.DepartmentID}");
                Console.WriteLine($"Service ID: {model.ServiceID}");
                Console.WriteLine($"Designation: {model.Designation}");
                Console.WriteLine($"Salary: {model.Salary}");

                if (ModelState.IsValid)
                {
                    Console.WriteLine("ModelState is valid. Attempting to update employee...");
                    EmployeeDAO.Instance.UpdateEmployee(model);
                    Console.WriteLine("Employee updated successfully");
                    return Json(new { success = true });
                }
                else
                {
                    Console.WriteLine("ModelState is not valid. Sending error response...");

                    // Lấy danh sách các lỗi xác thực từ ModelState và chuyển đổi thành danh sách thông báo lỗi
                    var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                    return Json(new { success = false, message = "Invalid input data", errors = errors });
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred: {ex.Message}");
                return Json(new { success = false, message = ex.Message });
            }
            finally
            {
                Console.WriteLine("End processing EditEmployee action");
            }
        }




        // Hàm sinh chuỗi ngẫu nhiên
        private string GenerateRandomString(int length)
        {
            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
            var random = new Random();
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        // Hàm sinh mật khẩu ngẫu nhiên
        private string GenerateRandomPassword(int length)
        {
            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            var random = new Random();
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}

Project_EOS/Areas/Admin/Views/EmployeesManage/EmployeeDetail.cshtml
@model Project_EOS.Models.Dao.EmployeeViewModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Employee Detail";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Employee Detail</title>
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/Content/style.css" />
</head>
<body>

    <div>
        <h2>@Model.EmployeeName works in the @Model.DepartmentName department, providing @Model.ServiceName services</h2>
    </div>

    <table class="table table-striped" id="numbered-table">
        <thead>
            <tr>
                <th>No.</th>
                <th class="name-column">Name</th>
                <th>Department</th>
                <th>Service</th>
                <th>Designation</th>
                <th>Email</th>
                <th>Salary</th>
                <th>Join Date</th>
                <th>Active</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>@Model.EmployeeName</td>
                <td>
                    <select id="editDepartment" disabled>
                        @foreach (var department in ViewBag.Departments as SelectList)
                        {
                            <option value="@department.Value" @(department.Value == Model.DepartmentID.ToString() ? "selected" : "")>@department.Text</option>
                        }
                    </select>
                </td>
                <td>
                    <select id="editService" disabled>
                        @foreach (var service in ViewBag.Services as SelectList)
                        {
                            <option value="@service.Value" @(service.Value == Model.ServiceID.ToString() ? "selected" : "")>@service.Text</option>
                        }
                    </select>
                </td>
                <td>
                    <input type="text" id="editDesignation" value="@Model.Designation" placeholder="@Model.Designation" disabled>
                </td>
                <td>@Model.Email</td>
                <td>
                    <input type="text" id="editSalary" value="@Model.Salary.ToString("C")" placeholder="@Model.Salary.ToString("C")" disabled>
                </td>
                <td>@Model.JoinDate.ToString("yyyy-MM-dd")</td>
                <td class="custom-checkbox">
                    <input type="checkbox" @(Model.Is_Active.HasValue && Model.Is_Active.Value ? "checked" : "") disabled>
                </td>
            </tr>
        </tbody>
    </table>
    <button id="editButton" data-employee-id="@Model.EmployeeID">Edit</button>
    <button id="saveEditBtn" style="display: none;" data-employee-id="@Model.EmployeeID">Save</button>
    <button id="cancelEditBtn" style="display: none;">Cancel</button>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/Areas/Admin/Scipts/Employee.js"></script>

</body>
</html>

Project_EOS/Areas/Admin/Views/EmployeesManage/Index.cshtml
@model IEnumerable<Project_EOS.Models.Dao.EmployeeViewModel>
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    List<Project_EOS.Models.Dao.EmployeeViewModel> employees = ViewBag.employees as List<Project_EOS.Models.Dao.EmployeeViewModel>;
    ViewBag.Title = "Employees";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/Content/style.css" />

</head>
<body>

    <div>
        <!-- Button to toggle form visibility -->
        <button id="showFormBtn" onclick="showCreateForm()">Add Employee</button>
        <!-- Add Employee Form -->
        <form id="addEmployeeForm" class="hidden">
            <div>
                <label for="EmployeeName">Employee Name</label>
                <input type="text" id="createEmployeeName" name="EmployeeName" placeholder="Employee Name" required />
            </div>
            <div>
                <label for="DepartmentID">Department</label>
                @Html.DropDownList("DepartmentID", ViewBag.Departments as SelectList, "Select Department", new { @id = "createDepartmentName", @class = "form-control", required = "required" })
            </div>
            <div>
                <label for="ServiceID">Service</label>
                @Html.DropDownList("ServiceID", ViewBag.Services as SelectList, "Select Service", new { @id = "createServiceName", @class = "form-control", required = "required" })
            </div>

            <div>
                <label for="Designation">Designation</label>
                <input type="text" id="createDesignation" name="Designation" placeholder="Designation" required />
            </div>
            <div>
                <label for="Email">Email</label>
                <input type="email" id="createEmail" name="Email" placeholder="Email" required />
            </div>
            <div>
                <label for="Salary">Salary</label>
                <input type="number" id="createSalary" name="Salary" placeholder="Salary" required />
            </div>
            <div>
                <label for="JoinDate">Join Date</label>
                <!-- Giá trị mặc định cho JoinDate được thiết lập ở phía Controller -->
                <input type="date" id="createJoinDate" name="JoinDate" required />
            </div>

            <input type="hidden" name="Is_Active" value="false" id="createActive" />

            <button type="button" onclick="saveNewEmployee()">Submit</button>

            <button type="button" id="cancelBtn" onclick="cancelCreate()">Cancel</button>
        </form>
    </div>


    <h2>Employees</h2>

    <table class="table table-striped" id="numbered-table">
        <thead>
            <tr>
                <th>No.</th>
                <th class="name-column">Name</th>
                <th>Department</th>
                <th>Service</th>
                <th>Designation</th>
                @*<th>Email</th>
                    <th>Salary</th>
                    <th>Join Date</th>*@
                <th>Active</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var employee in employees)
            {
                <tr>
                    <td></td>
                    <td>
                        <a href="@Url.Action("EmployeeDetail", "EmployeesManage", new { employeeID = employee.EmployeeID, employeeName = employee.EmployeeName })">
                            @employee.EmployeeName
                        </a>
                    </td>
                    <td>@employee.DepartmentName</td>
                    <td>@employee.ServiceName</td>
                    <td>@employee.Designation</td>
                    @*<td>@employee.Email</td>
                        <td>@employee.Salary</td>
                        <td>@employee.JoinDate.ToString("yyyy-MM-dd")</td>*@
                    <td class="custom-checkbox"><input type="checkbox" @(employee.Is_Active.HasValue && employee.Is_Active.Value ? "checked" : "") disabled></td>
                </tr>
            }
        </tbody>
    </table>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/Areas/Admin/Scripts/Employee.js"></script>


</body>
</html>